// Generated by CoffeeScript 1.3.3
(function() {
  var Itertools, exports;

  Itertools = (function() {

    function Itertools() {}

    Itertools.prototype.permutationsSync = function(arr, k) {
      return arr;
    };

    return Itertools;

  })();

  module.exports = exports = new Itertools();

}).call(this);
